version: '1.1.{build}'
image: Visual Studio 2017
branches:
    only:
    - master

init:
    - cmd: git config --global core.autocrlf true

before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore Fox.sln --verbosity m

build_script:
    - cmd: dotnet publish Fox.sln

deploy: off